apiVersion: v1
kind: ConfigMap
metadata:
  name: codepix-conf
data:
  #we created our database with "helm bitname", after instal we receive some instructions like, how to connect(host) password and etc..
  #here we put the same variables that we have in our .env file, but here we don`t put the 'dsnPostgres' with password
  env: |
    DB_TYPE_POSTGRES="postgres"
    AUTO_MIGRATE_DB_POSTGRES="true"
    DB_TYPE_TEST_POSTGRES="sqlite3" 
    DSN_TEST_POSTGRES=":memory:"
    ENV="dev"
    DEBUG="true"
    KAFKA_BOOTSTRAP_SERVERS="kafka:9092"
    KAFKA_CONSUMER_GROUP_ID="codepix"
    KAFKA_TRANSACTION_TOPIC="transactions"
    KAFKA_TRANSACTION_CONFIRMATIONTOPIC="transaction_confirmation"
