apiVersion: v1
kind: Secret
metadata:
  name: codepix-secret
type: Opaque
data:
  #dbname=codepix sslmode=disable user=postgres password=TUGfmIQ0gg host=postgres-postgresql.default.svc.cluster.local
  #the hash below is the string above encoded for base64 in the website: https://www.base64encode.org/
  DSN_POSTGRES: ZGJuYW1lPWNvZGVwaXggc3NsbW9kZT1kaXNhYmxlIHVzZXI9cG9zdGdyZXMgcGFzc3dvcmQ9VFVHZm1JUTBnZyBob3N0PXBvc3RncmVzLXBvc3RncmVzcWwuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbA==
