apiVersion: v1
kind: ConfigMap
metadata:
  name: bankapi-bbx-conf
data:
  #we created our database with "helm bitname", after instal we receive some instructions like, how to connect(host) password and etc..
  #here we put the same variables that we have in our .env file, but here we don`t put the password
  env: |
    BANK_CODE=001
    TYPEORM_CONNECTION=postgres
    TYPEORM_HOST=postgres-postgresql.default.svc.cluster.local
    TYPEORM_USERNAME=postgres
    TYPEORM_DATABASE=bank001
    TYPEORM_PORT=5432
    TYPEORM_ENTITIES=src/**/*.model.ts
    TYPEORM_ENTITIES_DIR=src/models
    TYPEORM_MIGRATIONS=src/migrations/**/*.ts
    TYPEORM_MIGRATIONS_DIR=src/migrations
    GRPC_URL=codepix-service:50051
    KAFKA_CLIENT_ID=codepix
    KAFKA_BROKER=kafka:9092
    KAFKA_CONSUMER_GROUP_ID=bank001
    KAFKA_TRANSACTION_TOPIC=transactions
    KAFKA_TRANSACTION_CONFIRMATION_TOPIC=transaction_confirmation
