version: '3'

services: 
  app: 
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: imersao-next-bank
    ports:
    - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  db:
    build: .docker/postgres
    container_name: imersao-next-bank-db
    tty: true
    volumes:
      - .docker/.pgdatabbx:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nest
