version: '3'

services: 
  app: 
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: 'imersao-next-bank'
    ports:
    - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: .docker/postgres
    container_name: 'imersao-next-bank-db'
    tty: true
    volumes:
      - .docker/.pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nest
    