apiVersion: v1
kind: Service
metadata:
  name: bank-frontend-bbx-service
spec:
  type: LoadBalancer # LoadBalancer type is to get a external IP
  selector:
    app: bank-frontend-bbx
  ports:
  - port: 3000

# we can start this service with port-forward, because locally our machine don't generates external IP
# to start using port forward: kubectl port-forward svc/bank-frontend-bbx-service 9090:3000