apiVersion: v1
kind: Service
metadata:
  name: bank-frontend-cter-service
spec:
  type: LoadBalancer # LoadBalancer type is to get a external IP
  selector:
    app: bank-frontend-cter
  ports:
  - port: 3000
  